/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package binescheleton;

import DatabaseModule.DataRow;
import Dialogs.ErrorDialog;

/**
 *
 * @author Ariel
 */
public class CreateAccountWindow extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountWindow
     */
    public CreateAccountWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        streetLabel = new javax.swing.JLabel();
        surnameLabel2 = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        postCodeLabel = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        numberLocalLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        loginTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        surnameTextField = new javax.swing.JTextField();
        surnameLabel1 = new javax.swing.JLabel();
        surnameLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();
        streetTextField = new javax.swing.JTextField();
        numberTextField = new javax.swing.JTextField();
        localNumberTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        postCodeTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        streetLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        streetLabel.setText("Ulica: ");

        surnameLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        surnameLabel2.setText("Adres");

        cityLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cityLabel.setText("Miasto: ");

        postCodeLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        postCodeLabel.setText("Kod pocztowy: ");

        numberLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numberLabel.setText("Nr. domu: ");

        numberLocalLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        numberLocalLabel.setText("Nr. lokalu: ");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Dane użytkownika");

        loginLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        loginLabel.setText("Login: ");

        nameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameLabel.setText("Imię: ");

        surnameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        surnameLabel.setText("Nazwisko: ");

        surnameLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        surnameLabel1.setText("Hasło:");

        surnameLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        surnameLabel3.setText("Potwierdź hasło:");

        saveButton.setText("Zapisz");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(surnameLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(surnameLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(surnameLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(surnameTextField))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(nameLabel)
                                    .addGap(13, 13, 13)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(surnameLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(postCodeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(postCodeTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(streetLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(streetTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberLabel)
                                    .addComponent(numberLocalLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberTextField)
                                    .addComponent(localNumberTextField))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel)
                            .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(surnameLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surnameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(surnameLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streetLabel)
                            .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberLabel)
                            .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberLocalLabel)
                            .addComponent(localNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postCodeLabel)
                            .addComponent(postCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityLabel)
                            .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(saveButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        if(checkInput())
        {
            
            if(!passwordField.getText().equals(confirmPasswordField.getText()))
            {
                Dialogs.ErrorDialog errorDialog = new ErrorDialog(this, true, "Podane hasła są różne!", "CreateAccountWindow", "saveButtonActionPerformed", "");
                errorDialog.setVisible(true);
                return;
            }
            
            DataRow row = new DataRow(loginTextField.getText());
            row.setTableName("users");
            row.setName(loginTextField.getText());
            row.addAttribute("userPassword", passwordField.getText());
            row.addAttribute("firstName", nameTextField.getText());
            row.addAttribute("surname", surnameTextField.getText());
            row.addAttribute("street", streetTextField.getText());
            row.addAttribute("number", numberTextField.getText());
            row.addAttribute("secondNumber", localNumberTextField.getText());
            row.addAttribute("postCode", postCodeTextField.getText());
            row.addAttribute("city", cityTextField.getText());
            try
            {
                DataVector.getInstance().dbManager.createUser(row);
                boolean result = DataVector.getInstance().dbManager.login(loginTextField.getText(), passwordField.getText());
                if(result)
                {
                    DataRow parameters = new DataRow();
                    parameters.setTableName("users");
                    parameters.addAttribute("name", loginTextField.getText());
                    row = DataVector.getInstance().dbManager.select(parameters).get(0);
                    MainWindow wind = new MainWindow(row);
                    DataVector.getInstance().setMainWindow(wind);
                    wind.setVisible(true);
                    this.dispose();

                } else {
                    Dialogs.ErrorDialog dialog = new ErrorDialog(this, true, "Błąd logowania!", "CreateAccountWindow", "login", "");
                    dialog.setVisible(true);
                    
                }
            } catch(Exception e) {
                Dialogs.ErrorDialog errorDialog = new ErrorDialog(this, true, e.getMessage(), "CreateAccountWindow", "saveButtonActionPerformed", "");
                errorDialog.setVisible(true);
            }
            
        } else {
            Dialogs.ErrorDialog errorDialog = new ErrorDialog(this, true, "Nie wypełniono wymaganych pól!", "CreateAccountWindow", "saveButtonActionPerformed", "");
            errorDialog.setVisible(true);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField localNumberTextField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel numberLocalLabel;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel postCodeLabel;
    private javax.swing.JTextField postCodeTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JLabel surnameLabel1;
    private javax.swing.JLabel surnameLabel2;
    private javax.swing.JLabel surnameLabel3;
    private javax.swing.JTextField surnameTextField;
    // End of variables declaration//GEN-END:variables
    private boolean checkInput()
    {
        boolean result = true;
        result = result && !loginTextField.getText().equals("");
        result = result && !nameTextField.getText().equals("");
        result = result && !surnameTextField.getText().equals("");
        result = result && !passwordField.getText().equals("");
        result = result && !confirmPasswordField.getText().equals("");
        result = result && !streetTextField.getText().equals("");
        result = result && !numberTextField.getText().equals("");
        result = result && !postCodeTextField.getText().equals("");
        result = result && !cityTextField.getText().equals("");
        return result;
    }
}
